### ISSUE TITLE
Griffith Valuation names

### ISSUE THREAD

**Issue by jkennedyie** [rory/osm-irish-townlands#108]
Sometimes Griffith Valuation names of townlands are different to the names in OSM and so the query link does not work.
I see this problem is solved in the census results with tags like name:census1901
I would like to propose a tag name:griffithsvaluation unless there is a better idea?

E.g. Millicent North - http://www.townlands.ie/kildare/clane/clane/clane/millicent-north/#records
This is in Griffith Valuation as "Millicent, North":
http://www.askaboutireland.ie/griffith-valuation/index.xml?action=doPlaceSearch&Submit.x=51&Submit.y=16&Submit=Submit&freetext=Millicent,%20North&countyname=Kildare&baronyname=Clane&parishname=Clane

I am happy to propose a Pull Request with a possible fix in the coming days.

**Comment by rory** [comment]
Sounds good.

**Comment by jkennedyie** [comment]
OK I committed changes to my existing pull request and updated the pull request text.
If you prefer a different approach pls shout.
Thanks!

**Comment by jkennedyie** [comment]
With this merge the following cases now can be handled by the tag name:griffithsvaluation:
* Different townland name in Griffith's. E.g. http://www.townlands.ie/kildare/clane/clane/clane/millicent-north/#records
* Different civil parish name in Griffith's. E.g. http://www.townlands.ie/kildare/connell/kilmeague/kilmeage-south/ballintine/#records
* Different barony name in Griffith's. E.g. http://www.townlands.ie/kildare/north-salt/kildrought/celbridge/aghards/#records

I will investigate making an automated update to apply name:griffithsvaluation where needed.
