### ISSUE TITLE
Mappers activity page is showing a double count of townlands mapped

### ISSUE THREAD

**Issue by DaCor1** [rory/osm-irish-townlands#81]
As an example, the page for mapper MikeOS shows 6 townlands added even though he has added only 3 by the looks of it

http://www.townlands.ie/mapper/MikeOS/

**Comment by IrlJidel** [comment]
Looks like duplicate relations and not a td.ie bug

http://www.openstreetmap.org/relation/4678503
http://www.openstreetmap.org/relation/4726163

**Comment by DaCor1** [comment]
ah ok. My mistake

**Comment by rory** [comment]
FYI I think those 2 relations don't share all the same ways, so there must be some overlapping ways there too.

Closing this as this is not a bug with this software.
