### ISSUE TITLE
Create a geometry-less CSV export file

### ISSUE THREAD

**Issue by DaCor1** [rory/osm-irish-townlands#83]
I dont know if the CSV is generating blank lines or if the data is corrupted somewhere along the process, but what I am seeing is:

- single row gaps appearing for no obvious reason following by
- a single row with a long series of columns (out to column ABL in excel) with 740+ long/lat coords

Some examples are for the following townlands
- Sessuegarry
- Gowla
- Ballynahinch

**Comment by DaCor1** [comment]
Gowla is a good example. Its on row 407 of todays CSV. 

Its like the values in the WKT column are also ending up in columns themselves. As a result, the info for Gowla is spread across 2 rows, with the first row simply a series of columns with the WKT values and the next row is the overflow

The single row gaps I referred to above, ignore that. Those were showing up because I deleted the WKT colum

**Comment by rory** [comment]
Weird. I've tried just now (so technically a different day's data). The townlands CSV works for me in QGis and in LibreOffice. However LibreOffice did give me a message about "maximum number of characters per cell". The first column is the geometry, and it can be very long.

CSV is a bit of a picky file format, and many applications (like spreadsheets) might not be expecting to have such large columns.

If you want to do analysis of the data, perhaps I could add a dump file that doesn't have the WKT/geometry column?

**Comment by DaCor1** [comment]
That would work..... If it's not too much trouble

**Comment by rory** [comment]
Done. You'll find the links on the download page as usual.

**Comment by DaCor1** [comment]
As handy as a small pot, ya are
