### ISSUE TITLE
when a CP is in >1 county, list it on each county page

### ISSUE THREAD

**Issue by rory** [rory/osm-irish-townlands#86]
e.g. clones is in Mon & Ferm. but isn't listed here http://www.townlands.ie/fermanagh/ or http://www.townlands.ie/monaghan/

**Comment by rory** [comment]
Fixed now. /cc @CliffordD

**Comment by CliffordD** [comment]
Its there any way to show just the parish in that county?  For example the Clones, Fermanagh page, is it possible to only show the townlands in the Fermanagh part of it?  http://www.townlands.ie/fermanagh/clones/  So there would be two pages, one for the Fermanagh section and one for the Monaghan part?
