### ISSUE TITLE
Rename Electoral Divisions to Electoral Divisions/Wards

### ISSUE THREAD

**Issue by DaCor1** [rory/osm-irish-townlands#88]
To account for different naming in NI

**Comment by CliffordD** [comment]
Wards are different from ED's.  A ward is probably on average a combination of about 3-6 ED's maybe more in rural areas.  I dont think it would be beneficial to rename them as it will only cause confusion. If the ward data in NI ever gets released so we can use it, then the wards can be mapped as a separate division.

**Comment by DaCor1** [comment]
ah ok, my understanding was they were the same, just named differently

**Comment by CliffordD** [comment]
Unfortunately not, that would be too simple!

**Comment by rory** [comment]
Since "ED" is a correct term in NI, I'm gonna close this issue.
