### ISSUE TITLE
Support name:census19XX for census links

### ISSUE THREAD

**Issue by rory** [rory/osm-irish-townlands#93]
Some townlands have different names in different censuses. This should be mapped as `name:census1901`/`name:census1911` etc. We should support that when constructing links to census look up.

**Comment by CliffordD** [comment]
An example is http://www.townlands.ie/fermanagh/magherastephana/aghalurcher/cornarooslan/

**Comment by rory** [comment]
this should be done now. Data update is running which should show it

**Comment by CliffordD** [comment]
Nice job, would it be possible to include this name as an alternative name on the townland page?  Maybe something like "Cornarooslan, also known as Cornarooslin (Source : National Census 1901)"

**Comment by rory** [comment]
It says that below in the Census section. "In the 1901 Census, Cornarooslan was recorded as Cornarooslin". Is that suffecient, or would you like that sort of text added to the top as well?

**Comment by rory** [comment]
As per @Boggety's suggestion, this should be added for all area types, not just townlands. Specifically, it should be added for EDs.

**Comment by rory** [comment]
This has been added for EDs
