### ISSUE TITLE
Search Engine Optimisation 

### ISSUE THREAD

**Issue by CliffordD** [rory/osm-irish-townlands#96]
It might be a good idea to include an introduction on the home page.   Maybe mention what a townland is, a bit about OSM.ie and how the OSM community are mapping them with out of copyright maps - maybe a link to the wiki ( http://wiki.openstreetmap.org/wiki/Ireland/Mapping_Townlands )

This would help search engine rank the website higher.  A few quality backlinks would also help for example, www.openstreetmap.ie, OSM wiki, OSM.ie Map Server, links to the 1901/1911 Census and Griffith Valuation.

**Comment by rory** [comment]
SEO is a great idea. I already try to do a bit of that. (Lots of links, sensible URLs and page titles).

Backlinks from those sites would be great, if you can ask them to link to townlands.ie.

**Comment by rory** [comment]
Gonna close that, since I'm already doing some SEO. I'm always interested in more approaches and getting higher rankings. If you have more specific advice, I'm all ears. :)
